// import { icons } from "antd/es/image/PreviewGroup";
import mastercard from "../../../public/mastercard_icon.svg";
export const employees = [
    {
        id: 1,
        name: "Abdujabbor Ibrohimov",
        gruop: "45",
        course: "10",
        icon: mastercard,
        status: "Settled",
        avatar: "https://i.pravatar.cc/40?img=1",
    },
    {
        
        id: 2,
        name: "Gulnora Rasulova",
        gruop: "41",
        course: "12",
        icon: mastercard,
        status: "Pending",
        avatar: "https://i.pravatar.cc/40?img=2",
    },
    {
        id: 3,
        name: "Nodirbek Yuldashev",
        gruop: "35",
        course: "23",
        icon: mastercard,
        status: "Failed",
        avatar: "https://i.pravatar.cc/40?img=3",
    },
    {
        id: 4,
        name: "Madinabonu Bozorova",
        gruop: "35",
        course: "23",
        icon: mastercard,
        status: "Failed",
        avatar: "https://i.pravatar.cc/40?img=3",
    },
    {
        id: 5,
        name: "Islom Abdullaev",
        gruop: "35",
        course: "23",
        icon: mastercard,
        status: "Failed",
        avatar: "https://i.pravatar.cc/40?img=3",
    },
    {
        id: 1,
        name: "Abdujabbor Ibrohimov",
        gruop: "39",
        course: "21",
        icon: mastercard,
        status: "Settled",
        avatar: "https://i.pravatar.cc/40?img=1",
    },
    {
        id: 2,
        name: "Gulnora Rasulova",
        gruop: "33",
        course: "12",
        icon: mastercard,
        status: "Pending",
        avatar: "https://i.pravatar.cc/40?img=2",
    },
    {
        id: 3,
        name: "Nodirbek Yuldashev",
        gruop: "44",
        course: "23",
        icon: mastercard,
        status: "Failed",
        avatar: "https://i.pravatar.cc/40?img=3",
    },
    {
        id: 4,
        name: "Madinabonu Bozorova",
        gruop: "35",
        course: "23",
        icon: mastercard,
        status: "Failed",
        avatar: "https://i.pravatar.cc/40?img=3",
    },
    {
        id: 5,
        name: "Islom Abdullaev",
        gruop: "35",
        course: "23",
        icon: mastercard,
        status: "Failed",
        avatar: "https://i.pravatar.cc/40?img=3",
    },
];
