import mastercard from "../../../public/mastercard_icon.svg";

export const students = [
  {
    id: 1,
    name: "Abdujabbor Ibrohimov",
    phone: "+998 94 412 70 70",
    course: "Frontend 05",
    email: "abdujabbor.ibrohimov@gmail.com",
    country: "Uzbekistan",
    city: "Tashkent",
    address: "Amir Temur Street 101",
    zip: "100100",
    invoiceId: "#00123045",
    payType: "Card",
    payReason: "Course Payment",
    payDate: "2025-06-20",
    icon: mastercard,
    pay: "**** 4567",
    price: "$850.00",
    status: "Settled",
    avatar: "https://i.pravatar.cc/40?img=1",
  },
  {
    id: 2,
    name: "Gulnora Rasulova",
    phone: "+998 94 412 90 65",
    course: "Frontend 05",
    email: "gulnora.rasulova@gmail.com",
    country: "Uzbekistan",
    city: "Tashkent",
    address: "Buyuk Ipak Yo‘li 23",
    zip: "100200",
    invoiceId: "#00123046",
    payType: "Card",
    payReason: "Course Payment",
    payDate: "2025-06-18",
    icon: mastercard,
    pay: "**** 4567",
    price: "$850.00",
    status: "Pending",
    avatar: "https://i.pravatar.cc/40?img=2",
  },
  {
    id: 3,
    name: "Nodirbek Yuldashev",
    phone: "+998 94 59 67 54",
    course: "Foundation 02",
    email: "nodirbek.yuldashev@gmail.com",
    country: "Uzbekistan",
    city: "Namangan",
    address: "Navbahor ko‘chasi 17",
    zip: "160105",
    invoiceId: "#00123047",
    payType: "Card",
    payReason: "Course Payment",
    payDate: "2025-06-15",
    icon: mastercard,
    pay: "**** 4567",
    price: "$850.00",
    status: "Failed",
    avatar: "https://i.pravatar.cc/40?img=3",
  },
  {
    id: 4,
    name: "Abdujabbor Ibrohimov",
    phone: "+998 94 412 70 70",
    course: "Frontend 05",
    email: "abdujabbor.ibrohimov2@gmail.com",
    country: "Uzbekistan",
    city: "Tashkent",
    address: "Minor Street 45",
    zip: "100110",
    invoiceId: "#00123048",
    payType: "Card",
    payReason: "Course Payment",
    payDate: "2025-06-12",
    icon: mastercard,
    pay: "**** 4567",
    price: "$850.00",
    status: "Settled",
    avatar: "https://i.pravatar.cc/40?img=1",
  },
  {
    id: 5,
    name: "Gulnora Rasulova",
    phone: "+998 94 412 90 65",
    course: "Frontend 05",
    email: "gulnora.rasulova2@gmail.com",
    country: "Uzbekistan",
    city: "Samarqand",
    address: "Registon Street 2",
    zip: "140101",
    invoiceId: "#00123049",
    payType: "Card",
    payReason: "Course Payment",
    payDate: "2025-06-10",
    icon: mastercard,
    pay: "**** 4567",
    price: "$850.00",
    status: "Pending",
    avatar: "https://i.pravatar.cc/40?img=2",
  },
  {
    id: 6,
    name: "Nodirbek Yuldashev",
    phone: "+998 94 59 67 54",
    course: "Foundation 02",
    email: "nodirbek.yuldashev2@gmail.com",
    country: "Uzbekistan",
    city: "Buxoro",
    address: "Sitorai Mohi Hosa ko‘chasi 10",
    zip: "200120",
    invoiceId: "#00123050",
    payType: "Card",
    payReason: "Course Payment",
    payDate: "2025-06-08",
    icon: mastercard,
    pay: "**** 4567",
    price: "$850.00",
    status: "Failed",
    avatar: "https://i.pravatar.cc/40?img=3",
  },
];
