// import { icons } from "antd/es/image/PreviewGroup";
import mastercard from "../../../public/mastercard_icon.svg";
export const students = [
  {
    id: 1,
    name: "Abdujabbor Ibrohimov",
    phone: "+998 94 412 70 70",
    course: "Frontend 05",
    icon: mastercard,
    pay: "**** 4567",
    price: "$850.00",
    status: "Settled",
    avatar: "https://i.pravatar.cc/40?img=1",
  },
  {
    id: 2,
    name: "Gulnora Rasulova",
    phone: "+998 94 412 90 65",
    course: "Frontend 05",
    icon: mastercard,
    pay: "**** 4567",
    price: "$850.00",
    status: "Pending",
    avatar: "https://i.pravatar.cc/40?img=2",
  },
  {
    id: 3,
    name: "Nodirbek Yuldashev",
    phone: "+998 94 59 67 54",
    course: "Foundation 02",
    icon: mastercard,
    pay: "**** 4567",
    price: "$850.00",
    status: "Failed",
    avatar: "https://i.pravatar.cc/40?img=3",
  },
  {
    id: 1,
    name: "Abdujabbor Ibrohimov",
    phone: "+998 94 412 70 70",
    course: "Frontend 05",
    icon: mastercard,
    pay: "**** 4567",
    price: "$850.00",
    status: "Settled",
    avatar: "https://i.pravatar.cc/40?img=1",
  },
  {
    id: 2,
    name: "Gulnora Rasulova",
    phone: "+998 94 412 90 65",
    course: "Frontend 05",
    icon: mastercard,
    pay: "**** 4567",
    price: "$850.00",
    status: "Pending",
    avatar: "https://i.pravatar.cc/40?img=2",
  },
  {
    id: 3,
    name: "Nodirbek Yuldashev",
    phone: "+998 94 59 67 54",
    course: "Foundation 02",
    icon: mastercard,
    pay: "**** 4567",
    price: "$850.00",
    status: "Failed",
    avatar: "https://i.pravatar.cc/40?img=3",
  },
];
