export const students = [
  {
    id: 1,
    name: "Python Beginners Batch A",
    course: "Python 05",
    mentor: "Jaloliddin Anorboyev",
    members: "45",
    status: "Active",
  },
  {
    id: 2,
    name: "Python Advanced Batch B",
    course: "Python 05",
    mentor: "Ali Valiyev",
    members: "41",
    status: "Inactive",
  },
  {
    id: 3,
    name: "Data Science Batch 3",
    course: "Data Sceince",
    mentor: "Jamshid Karimov",
    members: "23",
    status: "Active",
  },
  {
    id: 4,
    name: "SQL Training Batch A",
    course: "SQL",
    mentor: "Dildora Azizova",
    members: "34",
    status: "Inactive",
  },
  {
    id: 5,
    name: "UI/UX Design Training Batch A",
    course: "UI/UX",
    mentor: "Nigora Mirsagatova",
    members: "64",
    status: "Inactive",
  },
  {
    id: 6,
    name: "3D Animation Course Batch 2",
    course: "3D Modeling",
    mentor: "Shakhnoza Usmonova",
    members: "12",
    status: "Active",
  },
  {
    id: 7,
    name: "Digital Marketing Batch 5",
    course: "Digital Marketing",
    mentor: "Gulnoza Rahimova",
    members: "45",
    status: "Active",
  },
  {
    id: 8,
    name: "Excel for Business Batch 2",
    course: "Advanced Excel",
    mentor: "Sanjar Khudayberganov",
    members: "11",
    status: "Active",
  },
  {
    id: 9,
    name: "SEO Training Batch 2",
    course: "SEO",
    mentor: "Bek Zokirov",
    members: "26",
    status: "Inactive",
  },
];
